#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

CLANG_FORMAT_CMD="clang-format -i"
FILE_NAME_REGEXP=".*\.(cpp|hpp|h)$"
FILTER_BY_EXTENSION="grep -E $FILE_NAME_REGEXP"

cd ${DIR}

if [ "$1" = "all" ]; then
    find ${DIR} -path ${DIR}/external -prune -o -type f | $FILTER_BY_EXTENSION | xargs $CLANG_FORMAT_CMD
else
    { git diff --name-only && git ls-files -o; } | $FILTER_BY_EXTENSION | xargs $CLANG_FORMAT_CMD
fi
