#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
LOG_PREFIX="SETUP ENV"
. ${DIR}/common

check_is_as_user "root"

log "pacman bases update..."
pacman -Sy --noconfirm

log "pacman sudo installation..."
pacman -S sudo --noconfirm

# make nobody user available (shell is not set by default)
chsh -s /bin/bash nobody
# make nobody user sudoer
echo 'nobody ALL=(ALL) NOPASSWD: ALL' | sudo EDITOR='tee -a' visudo

log "done"
