#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
LOG_PREFIX="INSTALL"
. ${DIR}/common

check_is_as_user "developer"

log "pacman existing packages update..."
sudo pacman -Syu --noconfirm
log "pacman packages installation..."
sudo pacman -S --noconfirm --needed \
base-devel \
bash-completion \
binutils \
boost \
clang \
cmake \
gtest \
libffi \
make \
gdb \
git \
valgrind \
vim \
wget \
yajl

# a small trickery with libffi header paths
# because no one seems to care about them being fucked up
sudo ln -s /usr/lib/libffi-*/include/*.h /usr/include/

cd /tmp

log "package-query installation..."
git clone https://aur.archlinux.org/package-query.git
cd package-query
makepkg -si --noconfirm

cd /tmp

log "yaourt installation..."
git clone https://aur.archlinux.org/yaourt.git
cd yaourt
makepkg -si --noconfirm

log "done"
