#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
DIR=${SCRIPT_DIR}/../../
OPTIONS="
-it
--rm
--user=developer
-v $DIR:$DIR
-v $SCRIPT_DIR/.home/:/home/developer/:rw
-v /usr/share/fonts/:/usr/share/fonts/:ro
-w $DIR
-e DISPLAY=$DISPLAY
-v /tmp/.X11-unix:/tmp/.X11-unix
--cap-add=SYS_PTRACE
--security-opt seccomp=unconfined
--name interop_devenv_instance
--net=host
"

mkdir -p $SCRIPT_DIR/.home
ln -sf $HOME/.Xauthority $SCRIPT_DIR/.home
cp -rf $HOME/.ssh $SCRIPT_DIR/.home

docker run $OPTIONS islamboziev/interop_devenv_archlinux_gui:latest bash
