#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"/../../
OPTIONS="
-it
--rm
--user=developer
-v $DIR:$DIR
-v $HOME/.vscode/:/home/developer/.vscode/:rw
-v $HOME/.config/:/home/developer/.config/:rw
-v /usr/share/fonts/:/usr/share/fonts/:ro
-w $DIR
-e DISPLAY=$DISPLAY
-v /tmp/.X11-unix:/tmp/.X11-unix
-v $HOME/.Xauthority:/home/developer/.Xauthority:rw
--cap-add=SYS_PTRACE
--security-opt seccomp=unconfined
--name interop_devenv_instance
--net=host
"

docker run $OPTIONS islamboziev/interop_devenv_archlinux_gui:latest code .
