//
// Created by islam on 14.01.18.
//

#pragma once

#define INTEROP_MODULE_INITIALIZE _interop_module_initialize
#define INTEROP_MODULE_REGISTER _interop_module_register
#define INTEROP_MODULE_METADATA _interop_module_metadata
#define INTEROP_FRAMEWORK_ABI_VERSION _interop_framework_abi_version

#define __INTEROP_STRINGIFY__(x) #x
#define __INTEROP_STRINGIFY(x) __INTEROP_STRINGIFY__(x)

#define INTEROP_MODULE_INITIALIZE_STR __INTEROP_STRINGIFY(INTEROP_MODULE_INITIALIZE)
#define INTEROP_MODULE_REGISTER_STR __INTEROP_STRINGIFY(INTEROP_MODULE_REGISTER)
#define INTEROP_MODULE_METADATA_STR __INTEROP_STRINGIFY(INTEROP_MODULE_METADATA)
#define INTEROP_FRAMEWORK_API_VERSION_STR __INTEROP_STRINGIFY(INTEROP_FRAMEWORK_ABI_VERSION)
