//
// Created by islam on 14.01.18.
//

#pragma once

#define MOSAIC_MODULE_INITIALIZE        _mosaic_module_initialize
#define MOSAIC_MODULE_REGISTER          _mosaic_module_register
#define MOSAIC_MODULE_METADATA          _mosaic_module_metadata
#define MOSAIC_FRAMEWORK_ABI_VERSION    _mosaic_framework_abi_version

#define __MOSAIC_STRINGIFY__(x) #x
#define __MOSAIC_STRINGIFY(x) __MOSAIC_STRINGIFY__(x)

#define MOSAIC_MODULE_INITIALIZE_STR        __MOSAIC_STRINGIFY(MOSAIC_MODULE_INITIALIZE)
#define MOSAIC_MODULE_REGISTER_STR          __MOSAIC_STRINGIFY(MOSAIC_MODULE_REGISTER)
#define MOSAIC_MODULE_METADATA_STR          __MOSAIC_STRINGIFY(MOSAIC_MODULE_METADATA)
#define MOSAIC_FRAMEWORK_API_VERSION_STR    __MOSAIC_STRINGIFY(MOSAIC_FRAMEWORK_ABI_VERSION)
